version: '3'

services:
  app:
    image: wendelladriel/laravel-hut
    container_name: laravel-hut
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/usr/src/app
